### ISSUE TITLE
telemetry_metrics-1.0

### ISSUE THREAD

**Issue by ewildgoose** [mobius-home/mobius#93]
Hi, could you please bump telemetry_metrics to 1.0.0. It's compatible with 0.6, just they decided to call it stable now

**Comment by fhunleth** [comment]
@ewildgoose Thanks for seeing this. Could you send a PR?

**Comment by ewildgoose** [comment]
It will also be useful to do a release now, easier to pull in these changes via mix.

Thanks!

**Comment by ewildgoose** [comment]
Can I ping again for a release please? (At risk of playing the same game as the xz library maintainer - trying to bump dependencies in my dependent project!)

**Comment by fhunleth** [comment]
Hahahahha. Yeah, sorry for the delay.

I posted a v0.6.1 release. I noticed some trivial issues and went ahead and fixed them. Let me know if I messed it up.
